// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaRKgQMAKZO5iDfJZquXLZzIlupqrtTYY',
    appId: '1:831781150590:web:c08ba384c769594400dd2f',
    messagingSenderId: '831781150590',
    projectId: 'taskassistant-e4a70',
    authDomain: 'taskassistant-e4a70.firebaseapp.com',
    storageBucket: 'taskassistant-e4a70.firebasestorage.app',
    measurementId: 'G-ZDHYKHZ94Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX-_llTatXbQijbJXBzBvai3nXidWrP_A',
    appId: '1:831781150590:android:02ae8c9a3658481a00dd2f',
    messagingSenderId: '831781150590',
    projectId: 'taskassistant-e4a70',
    storageBucket: 'taskassistant-e4a70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_DSXUcxSV_N1e9prSXeE-b7UEETHELdU',
    appId: '1:831781150590:ios:70aa5d9cdbf315ad00dd2f',
    messagingSenderId: '831781150590',
    projectId: 'taskassistant-e4a70',
    storageBucket: 'taskassistant-e4a70.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_DSXUcxSV_N1e9prSXeE-b7UEETHELdU',
    appId: '1:831781150590:ios:70aa5d9cdbf315ad00dd2f',
    messagingSenderId: '831781150590',
    projectId: 'taskassistant-e4a70',
    storageBucket: 'taskassistant-e4a70.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaRKgQMAKZO5iDfJZquXLZzIlupqrtTYY',
    appId: '1:831781150590:web:a9760b038d571b7200dd2f',
    messagingSenderId: '831781150590',
    projectId: 'taskassistant-e4a70',
    authDomain: 'taskassistant-e4a70.firebaseapp.com',
    storageBucket: 'taskassistant-e4a70.firebasestorage.app',
    measurementId: 'G-14ZE5ZEWS9',
  );
}
